elton1:
  image: elton:latest
  ports:
    - 12345
    - 4949
  command: examples/start.sh master
  environment:
    - MASTER=elton_elton1_1
    - MASTERS1=elton_elton2_1
    - BACKUP=elton_backup_1

elton2:
  image: elton:latest
  ports:
    - 12345
    - 4949
  links:
    - elton1:elton1
  command: examples/start.sh master
  environment:
    - MASTER=elton_elton2_1
    - MASTERS1=elton_elton1_1
    - BACKUP=elton_backup_1

backup:
  image: elton:latest
  ports:
    - 34567
    - 4949
  links:
    - elton1:elton1
    - elton2:elton2
  environment:
    - SLAVE=elton_slave1_1
    - MASTER=elton_elton1_1
  command: examples/start.sh backup

eltonfs:
  image: eltonfs:latest
  ports:
    - 51823
    - 4949
  links:
    - elton1:elton1
  privileged: true

munin:
  image: munin:latest
  ports:
    - 8080:80
  links:
    - elton1:elton1
    - elton2:elton2
    - backup:backup
    - eltonfs:eltonfs
  environment:
    - NODES="elton1:elton1 elton2:elton2 backup:backup eltonfs:eltonfs"
