// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package proto2

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventType int32

const (
	EventType_ET_ALL                  EventType = 0
	EventType_ET_STATUS_CHANGED       EventType = 10
	EventType_ET_SERVER_ADDED         EventType = 1
	EventType_ET_SERVER_STOPPING      EventType = 2
	EventType_ET_SERVER_STOPPED       EventType = 3
	EventType_ET_SERVER_DETACHING     EventType = 4
	EventType_ET_SERVER_DETACHED      EventType = 5
	EventType_ET_OBJECT_CREATED       EventType = 6
	EventType_ET_OBJECT_DELETED       EventType = 7
	EventType_ET_OBJECT_CACHE_CREATED EventType = 8
	EventType_ET_OBJECT_CACHE_DELETED EventType = 9
)

var EventType_name = map[int32]string{
	0:  "ET_ALL",
	10: "ET_STATUS_CHANGED",
	1:  "ET_SERVER_ADDED",
	2:  "ET_SERVER_STOPPING",
	3:  "ET_SERVER_STOPPED",
	4:  "ET_SERVER_DETACHING",
	5:  "ET_SERVER_DETACHED",
	6:  "ET_OBJECT_CREATED",
	7:  "ET_OBJECT_DELETED",
	8:  "ET_OBJECT_CACHE_CREATED",
	9:  "ET_OBJECT_CACHE_DELETED",
}

var EventType_value = map[string]int32{
	"ET_ALL":                  0,
	"ET_STATUS_CHANGED":       10,
	"ET_SERVER_ADDED":         1,
	"ET_SERVER_STOPPING":      2,
	"ET_SERVER_STOPPED":       3,
	"ET_SERVER_DETACHING":     4,
	"ET_SERVER_DETACHED":      5,
	"ET_OBJECT_CREATED":       6,
	"ET_OBJECT_DELETED":       7,
	"ET_OBJECT_CACHE_CREATED": 8,
	"ET_OBJECT_CACHE_DELETED": 9,
}

func (x EventType) String() string {
	return proto.EnumName(EventType_name, int32(x))
}

func (EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

// ==== State Transition Diagram ====
//
// [SS_UNAVAILABLE]
//       |
// +-----|---------------+
// |     V               |
// |  [SS_INIT_PHASE_0]  |
// |     |               |
// |     V               |
// |  [SS_INIT_PHASE_1]  |
// |     |               |
// |     V               |
// |  [SS_INIT_PHASE_2]  |
// |     |               |
// +-----|---------------+
//       |
// +-----|-------------------------+
// |     V                         |
// |  [SS_OPERATING_RW] <-------+  |
// |     |                      |  |
// |     V                      |  |
// |  [SS_OPERATING_RW_TO_RO]   |  |
// |     |                      |  |
// |     V                      |  |
// |  [SS_OPERATING_RO] --------+  |
// |     |                         |
// +-----|-------------------------+
//       V
// [SHUTDOWN]
type SystemStatus int32

const (
	SystemStatus_SS_UNAVAILABLE SystemStatus = 0
	// launcherが起動した状態。
	SystemStatus_SS_INIT_PHASE_0 SystemStatus = 10
	// 各サブシステムが起動中の状態。
	SystemStatus_SS_INIT_PHASE_1 SystemStatus = 11
	// 各サブシステムが起動完了した状態。
	SystemStatus_SS_INIT_PHASE_2 SystemStatus = 12
	// 通常運用の状態。
	SystemStatus_SS_OPERATING_RW SystemStatus = 20
	// Read Onlyモードに移行中の状態
	SystemStatus_SS_OPERATING_RW_TO_RO SystemStatus = 21
	// Read Onlyモードで運用中。
	SystemStatus_SS_OPERATING_RO SystemStatus = 22
	// 各サブシステムのプロセスを終了している状態。
	SystemStatus_SS_SHUTDOWN SystemStatus = 30
)

var SystemStatus_name = map[int32]string{
	0:  "SS_UNAVAILABLE",
	10: "SS_INIT_PHASE_0",
	11: "SS_INIT_PHASE_1",
	12: "SS_INIT_PHASE_2",
	20: "SS_OPERATING_RW",
	21: "SS_OPERATING_RW_TO_RO",
	22: "SS_OPERATING_RO",
	30: "SS_SHUTDOWN",
}

var SystemStatus_value = map[string]int32{
	"SS_UNAVAILABLE":        0,
	"SS_INIT_PHASE_0":       10,
	"SS_INIT_PHASE_1":       11,
	"SS_INIT_PHASE_2":       12,
	"SS_OPERATING_RW":       20,
	"SS_OPERATING_RW_TO_RO": 21,
	"SS_OPERATING_RO":       22,
	"SS_SHUTDOWN":           30,
}

func (x SystemStatus) String() string {
	return proto.EnumName(SystemStatus_name, int32(x))
}

func (SystemStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

// ==== State Transition Diagram ====
//
//       [SSS_UNKNOWN]
//          |
//          v
//   +-- [SSS_STOPPED]  <----+
//   |      |                |
//   |      v                |
//   +-- [SSS_STARTING]      |
//   |      |                |
//   |      v                |
//   +-- [SSS_STARTED]       |
//   |      |                |
//   |      v                |
//   +-- [SSS_STOPPING]  ----+
//   |
//   V
// [Failed]
type SubServiceStatus int32

const (
	SubServiceStatus_SSS_UNKNOWN   SubServiceStatus = 0
	SubServiceStatus_SSS_STOPPED   SubServiceStatus = 1
	SubServiceStatus_SSS_STARTING  SubServiceStatus = 2
	SubServiceStatus_SSS_OPERATING SubServiceStatus = 3
	SubServiceStatus_SSS_STOPPING  SubServiceStatus = 4
	SubServiceStatus_SSS_FAILED    SubServiceStatus = 5
)

var SubServiceStatus_name = map[int32]string{
	0: "SSS_UNKNOWN",
	1: "SSS_STOPPED",
	2: "SSS_STARTING",
	3: "SSS_OPERATING",
	4: "SSS_STOPPING",
	5: "SSS_FAILED",
}

var SubServiceStatus_value = map[string]int32{
	"SSS_UNKNOWN":   0,
	"SSS_STOPPED":   1,
	"SSS_STARTING":  2,
	"SSS_OPERATING": 3,
	"SSS_STOPPING":  4,
	"SSS_FAILED":    5,
}

func (x SubServiceStatus) String() string {
	return proto.EnumName(SubServiceStatus_name, int32(x))
}

func (SubServiceStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

// ==== State Transition Diagram ====
//
// [OS_UNKNOWN]
//    |
//    v
// [OS_CREATING]
//    |  +------------------+
//    v  v                  |
// [OS_CREATED]  ----->  [OS_LOST]
//    |                     |
//    v                     |
// [OS_DELETING] <----------+
//    |
//    v
// [OS_DELETED]
type ObjectStatus int32

const (
	ObjectStatus_OS_UNKNOWN  ObjectStatus = 0
	ObjectStatus_OS_CREATING ObjectStatus = 1
	ObjectStatus_OS_CREATED  ObjectStatus = 2
	ObjectStatus_OS_LOST     ObjectStatus = 3
	ObjectStatus_OS_DELETING ObjectStatus = 4
	ObjectStatus_OS_DELETED  ObjectStatus = 5
)

var ObjectStatus_name = map[int32]string{
	0: "OS_UNKNOWN",
	1: "OS_CREATING",
	2: "OS_CREATED",
	3: "OS_LOST",
	4: "OS_DELETING",
	5: "OS_DELETED",
}

var ObjectStatus_value = map[string]int32{
	"OS_UNKNOWN":  0,
	"OS_CREATING": 1,
	"OS_CREATED":  2,
	"OS_LOST":     3,
	"OS_DELETING": 4,
	"OS_DELETED":  5,
}

func (x ObjectStatus) String() string {
	return proto.EnumName(ObjectStatus_name, int32(x))
}

func (ObjectStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

type SubsystemType int32

const (
	SubsystemType_UnknownSubsystemType    SubsystemType = 0
	SubsystemType_ControllerSubsystemType SubsystemType = 1
	SubsystemType_StorageSubsystemType    SubsystemType = 2
	SubsystemType_ObjectSubsystemType     SubsystemType = 3
	SubsystemType_SchedulerSubsystemType  SubsystemType = 4
)

var SubsystemType_name = map[int32]string{
	0: "UnknownSubsystemType",
	1: "ControllerSubsystemType",
	2: "StorageSubsystemType",
	3: "ObjectSubsystemType",
	4: "SchedulerSubsystemType",
}

var SubsystemType_value = map[string]int32{
	"UnknownSubsystemType":    0,
	"ControllerSubsystemType": 1,
	"StorageSubsystemType":    2,
	"ObjectSubsystemType":     3,
	"SchedulerSubsystemType":  4,
}

func (x SubsystemType) String() string {
	return proto.EnumName(SubsystemType_name, int32(x))
}

func (SubsystemType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

type ServiceType int32

const (
	ServiceType_UnknownServiceType   ServiceType = 0
	ServiceType_ListenerServiceType  ServiceType = 1
	ServiceType_DelivererServiceType ServiceType = 2
)

var ServiceType_name = map[int32]string{
	0: "UnknownServiceType",
	1: "ListenerServiceType",
	2: "DelivererServiceType",
}

var ServiceType_value = map[string]int32{
	"UnknownServiceType":   0,
	"ListenerServiceType":  1,
	"DelivererServiceType": 2,
}

func (x ServiceType) String() string {
	return proto.EnumName(ServiceType_name, int32(x))
}

func (ServiceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type ServerInfo struct {
	Guid                 string        `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	SubsystemType        SubsystemType `protobuf:"varint,4,opt,name=subsystemType,proto3,enum=proto2.SubsystemType" json:"subsystemType,omitempty"`
	ServiceType          ServiceType   `protobuf:"varint,5,opt,name=serviceType,proto3,enum=proto2.ServiceType" json:"serviceType,omitempty"`
	Group                []string      `protobuf:"bytes,2,rep,name=group,proto3" json:"group,omitempty"`
	Address              string        `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ServerInfo) Reset()         { *m = ServerInfo{} }
func (m *ServerInfo) String() string { return proto.CompactTextString(m) }
func (*ServerInfo) ProtoMessage()    {}
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *ServerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerInfo.Unmarshal(m, b)
}
func (m *ServerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerInfo.Marshal(b, m, deterministic)
}
func (m *ServerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerInfo.Merge(m, src)
}
func (m *ServerInfo) XXX_Size() int {
	return xxx_messageInfo_ServerInfo.Size(m)
}
func (m *ServerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ServerInfo proto.InternalMessageInfo

func (m *ServerInfo) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

func (m *ServerInfo) GetSubsystemType() SubsystemType {
	if m != nil {
		return m.SubsystemType
	}
	return SubsystemType_UnknownSubsystemType
}

func (m *ServerInfo) GetServiceType() ServiceType {
	if m != nil {
		return m.ServiceType
	}
	return ServiceType_UnknownServiceType
}

func (m *ServerInfo) GetGroup() []string {
	if m != nil {
		return m.Group
	}
	return nil
}

func (m *ServerInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type ServerQuery struct {
	SubsystemType        SubsystemType `protobuf:"varint,1,opt,name=subsystemType,proto3,enum=proto2.SubsystemType" json:"subsystemType,omitempty"`
	ServiceType          ServiceType   `protobuf:"varint,2,opt,name=serviceType,proto3,enum=proto2.ServiceType" json:"serviceType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ServerQuery) Reset()         { *m = ServerQuery{} }
func (m *ServerQuery) String() string { return proto.CompactTextString(m) }
func (*ServerQuery) ProtoMessage()    {}
func (*ServerQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *ServerQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerQuery.Unmarshal(m, b)
}
func (m *ServerQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerQuery.Marshal(b, m, deterministic)
}
func (m *ServerQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerQuery.Merge(m, src)
}
func (m *ServerQuery) XXX_Size() int {
	return xxx_messageInfo_ServerQuery.Size(m)
}
func (m *ServerQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerQuery.DiscardUnknown(m)
}

var xxx_messageInfo_ServerQuery proto.InternalMessageInfo

func (m *ServerQuery) GetSubsystemType() SubsystemType {
	if m != nil {
		return m.SubsystemType
	}
	return SubsystemType_UnknownSubsystemType
}

func (m *ServerQuery) GetServiceType() ServiceType {
	if m != nil {
		return m.ServiceType
	}
	return ServiceType_UnknownServiceType
}

type ObjectInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version              uint64   `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectInfo) Reset()         { *m = ObjectInfo{} }
func (m *ObjectInfo) String() string { return proto.CompactTextString(m) }
func (*ObjectInfo) ProtoMessage()    {}
func (*ObjectInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *ObjectInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectInfo.Unmarshal(m, b)
}
func (m *ObjectInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectInfo.Marshal(b, m, deterministic)
}
func (m *ObjectInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectInfo.Merge(m, src)
}
func (m *ObjectInfo) XXX_Size() int {
	return xxx_messageInfo_ObjectInfo.Size(m)
}
func (m *ObjectInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectInfo proto.InternalMessageInfo

func (m *ObjectInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ObjectInfo) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

type Object struct {
	Info                 *ObjectInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Body                 []byte      `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Object) Reset()         { *m = Object{} }
func (m *Object) String() string { return proto.CompactTextString(m) }
func (*Object) ProtoMessage()    {}
func (*Object) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *Object) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Object.Unmarshal(m, b)
}
func (m *Object) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Object.Marshal(b, m, deterministic)
}
func (m *Object) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Object.Merge(m, src)
}
func (m *Object) XXX_Size() int {
	return xxx_messageInfo_Object.Size(m)
}
func (m *Object) XXX_DiscardUnknown() {
	xxx_messageInfo_Object.DiscardUnknown(m)
}

var xxx_messageInfo_Object proto.InternalMessageInfo

func (m *Object) GetInfo() *ObjectInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *Object) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type ObjectCache struct {
	Obj                  *ObjectInfo `protobuf:"bytes,1,opt,name=obj,proto3" json:"obj,omitempty"`
	ServerInfo           *ServerInfo `protobuf:"bytes,2,opt,name=serverInfo,proto3" json:"serverInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ObjectCache) Reset()         { *m = ObjectCache{} }
func (m *ObjectCache) String() string { return proto.CompactTextString(m) }
func (*ObjectCache) ProtoMessage()    {}
func (*ObjectCache) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *ObjectCache) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectCache.Unmarshal(m, b)
}
func (m *ObjectCache) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectCache.Marshal(b, m, deterministic)
}
func (m *ObjectCache) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectCache.Merge(m, src)
}
func (m *ObjectCache) XXX_Size() int {
	return xxx_messageInfo_ObjectCache.Size(m)
}
func (m *ObjectCache) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectCache.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectCache proto.InternalMessageInfo

func (m *ObjectCache) GetObj() *ObjectInfo {
	if m != nil {
		return m.Obj
	}
	return nil
}

func (m *ObjectCache) GetServerInfo() *ServerInfo {
	if m != nil {
		return m.ServerInfo
	}
	return nil
}

type ObjectPath struct {
	Obj                  *ObjectInfo `protobuf:"bytes,1,opt,name=obj,proto3" json:"obj,omitempty"`
	Path                 string      `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ObjectPath) Reset()         { *m = ObjectPath{} }
func (m *ObjectPath) String() string { return proto.CompactTextString(m) }
func (*ObjectPath) ProtoMessage()    {}
func (*ObjectPath) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *ObjectPath) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectPath.Unmarshal(m, b)
}
func (m *ObjectPath) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectPath.Marshal(b, m, deterministic)
}
func (m *ObjectPath) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectPath.Merge(m, src)
}
func (m *ObjectPath) XXX_Size() int {
	return xxx_messageInfo_ObjectPath.Size(m)
}
func (m *ObjectPath) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectPath.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectPath proto.InternalMessageInfo

func (m *ObjectPath) GetObj() *ObjectInfo {
	if m != nil {
		return m.Obj
	}
	return nil
}

func (m *ObjectPath) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type Status struct {
	Writable             bool         `protobuf:"varint,1,opt,name=writable,proto3" json:"writable,omitempty"`
	RunLevel             SystemStatus `protobuf:"varint,2,opt,name=runLevel,proto3,enum=proto2.SystemStatus" json:"runLevel,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetWritable() bool {
	if m != nil {
		return m.Writable
	}
	return false
}

func (m *Status) GetRunLevel() SystemStatus {
	if m != nil {
		return m.RunLevel
	}
	return SystemStatus_SS_UNAVAILABLE
}

type EventListenerInfo struct {
	ServerInfo           *ServerInfo `protobuf:"bytes,1,opt,name=serverInfo,proto3" json:"serverInfo,omitempty"`
	Type                 EventType   `protobuf:"varint,2,opt,name=type,proto3,enum=proto2.EventType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *EventListenerInfo) Reset()         { *m = EventListenerInfo{} }
func (m *EventListenerInfo) String() string { return proto.CompactTextString(m) }
func (*EventListenerInfo) ProtoMessage()    {}
func (*EventListenerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{8}
}

func (m *EventListenerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventListenerInfo.Unmarshal(m, b)
}
func (m *EventListenerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventListenerInfo.Marshal(b, m, deterministic)
}
func (m *EventListenerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventListenerInfo.Merge(m, src)
}
func (m *EventListenerInfo) XXX_Size() int {
	return xxx_messageInfo_EventListenerInfo.Size(m)
}
func (m *EventListenerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_EventListenerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_EventListenerInfo proto.InternalMessageInfo

func (m *EventListenerInfo) GetServerInfo() *ServerInfo {
	if m != nil {
		return m.ServerInfo
	}
	return nil
}

func (m *EventListenerInfo) GetType() EventType {
	if m != nil {
		return m.Type
	}
	return EventType_ET_ALL
}

type AllEventListenerInfo struct {
	Servers              []*EventListenerInfo `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	Type                 EventType            `protobuf:"varint,2,opt,name=type,proto3,enum=proto2.EventType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AllEventListenerInfo) Reset()         { *m = AllEventListenerInfo{} }
func (m *AllEventListenerInfo) String() string { return proto.CompactTextString(m) }
func (*AllEventListenerInfo) ProtoMessage()    {}
func (*AllEventListenerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{9}
}

func (m *AllEventListenerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllEventListenerInfo.Unmarshal(m, b)
}
func (m *AllEventListenerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllEventListenerInfo.Marshal(b, m, deterministic)
}
func (m *AllEventListenerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllEventListenerInfo.Merge(m, src)
}
func (m *AllEventListenerInfo) XXX_Size() int {
	return xxx_messageInfo_AllEventListenerInfo.Size(m)
}
func (m *AllEventListenerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AllEventListenerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AllEventListenerInfo proto.InternalMessageInfo

func (m *AllEventListenerInfo) GetServers() []*EventListenerInfo {
	if m != nil {
		return m.Servers
	}
	return nil
}

func (m *AllEventListenerInfo) GetType() EventType {
	if m != nil {
		return m.Type
	}
	return EventType_ET_ALL
}

type EventDelivererInfo struct {
	ServerInfo           *ServerInfo `protobuf:"bytes,1,opt,name=serverInfo,proto3" json:"serverInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *EventDelivererInfo) Reset()         { *m = EventDelivererInfo{} }
func (m *EventDelivererInfo) String() string { return proto.CompactTextString(m) }
func (*EventDelivererInfo) ProtoMessage()    {}
func (*EventDelivererInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{10}
}

func (m *EventDelivererInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventDelivererInfo.Unmarshal(m, b)
}
func (m *EventDelivererInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventDelivererInfo.Marshal(b, m, deterministic)
}
func (m *EventDelivererInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventDelivererInfo.Merge(m, src)
}
func (m *EventDelivererInfo) XXX_Size() int {
	return xxx_messageInfo_EventDelivererInfo.Size(m)
}
func (m *EventDelivererInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_EventDelivererInfo.DiscardUnknown(m)
}

var xxx_messageInfo_EventDelivererInfo proto.InternalMessageInfo

func (m *EventDelivererInfo) GetServerInfo() *ServerInfo {
	if m != nil {
		return m.ServerInfo
	}
	return nil
}

type ListenResult struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListenResult) Reset()         { *m = ListenResult{} }
func (m *ListenResult) String() string { return proto.CompactTextString(m) }
func (*ListenResult) ProtoMessage()    {}
func (*ListenResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{11}
}

func (m *ListenResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListenResult.Unmarshal(m, b)
}
func (m *ListenResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListenResult.Marshal(b, m, deterministic)
}
func (m *ListenResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListenResult.Merge(m, src)
}
func (m *ListenResult) XXX_Size() int {
	return xxx_messageInfo_ListenResult.Size(m)
}
func (m *ListenResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ListenResult.DiscardUnknown(m)
}

var xxx_messageInfo_ListenResult proto.InternalMessageInfo

func (m *ListenResult) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type UnlistenResult struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnlistenResult) Reset()         { *m = UnlistenResult{} }
func (m *UnlistenResult) String() string { return proto.CompactTextString(m) }
func (*UnlistenResult) ProtoMessage()    {}
func (*UnlistenResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{12}
}

func (m *UnlistenResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnlistenResult.Unmarshal(m, b)
}
func (m *UnlistenResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnlistenResult.Marshal(b, m, deterministic)
}
func (m *UnlistenResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnlistenResult.Merge(m, src)
}
func (m *UnlistenResult) XXX_Size() int {
	return xxx_messageInfo_UnlistenResult.Size(m)
}
func (m *UnlistenResult) XXX_DiscardUnknown() {
	xxx_messageInfo_UnlistenResult.DiscardUnknown(m)
}

var xxx_messageInfo_UnlistenResult proto.InternalMessageInfo

func (m *UnlistenResult) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ListenStatusChangesResult struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListenStatusChangesResult) Reset()         { *m = ListenStatusChangesResult{} }
func (m *ListenStatusChangesResult) String() string { return proto.CompactTextString(m) }
func (*ListenStatusChangesResult) ProtoMessage()    {}
func (*ListenStatusChangesResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{13}
}

func (m *ListenStatusChangesResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListenStatusChangesResult.Unmarshal(m, b)
}
func (m *ListenStatusChangesResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListenStatusChangesResult.Marshal(b, m, deterministic)
}
func (m *ListenStatusChangesResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListenStatusChangesResult.Merge(m, src)
}
func (m *ListenStatusChangesResult) XXX_Size() int {
	return xxx_messageInfo_ListenStatusChangesResult.Size(m)
}
func (m *ListenStatusChangesResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ListenStatusChangesResult.DiscardUnknown(m)
}

var xxx_messageInfo_ListenStatusChangesResult proto.InternalMessageInfo

func (m *ListenStatusChangesResult) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type UnlistenStatusChangesResult struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnlistenStatusChangesResult) Reset()         { *m = UnlistenStatusChangesResult{} }
func (m *UnlistenStatusChangesResult) String() string { return proto.CompactTextString(m) }
func (*UnlistenStatusChangesResult) ProtoMessage()    {}
func (*UnlistenStatusChangesResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{14}
}

func (m *UnlistenStatusChangesResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnlistenStatusChangesResult.Unmarshal(m, b)
}
func (m *UnlistenStatusChangesResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnlistenStatusChangesResult.Marshal(b, m, deterministic)
}
func (m *UnlistenStatusChangesResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnlistenStatusChangesResult.Merge(m, src)
}
func (m *UnlistenStatusChangesResult) XXX_Size() int {
	return xxx_messageInfo_UnlistenStatusChangesResult.Size(m)
}
func (m *UnlistenStatusChangesResult) XXX_DiscardUnknown() {
	xxx_messageInfo_UnlistenStatusChangesResult.DiscardUnknown(m)
}

var xxx_messageInfo_UnlistenStatusChangesResult proto.InternalMessageInfo

func (m *UnlistenStatusChangesResult) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto2.EventType", EventType_name, EventType_value)
	proto.RegisterEnum("proto2.SystemStatus", SystemStatus_name, SystemStatus_value)
	proto.RegisterEnum("proto2.SubServiceStatus", SubServiceStatus_name, SubServiceStatus_value)
	proto.RegisterEnum("proto2.ObjectStatus", ObjectStatus_name, ObjectStatus_value)
	proto.RegisterEnum("proto2.SubsystemType", SubsystemType_name, SubsystemType_value)
	proto.RegisterEnum("proto2.ServiceType", ServiceType_name, ServiceType_value)
	proto.RegisterType((*Empty)(nil), "proto2.Empty")
	proto.RegisterType((*ServerInfo)(nil), "proto2.ServerInfo")
	proto.RegisterType((*ServerQuery)(nil), "proto2.ServerQuery")
	proto.RegisterType((*ObjectInfo)(nil), "proto2.ObjectInfo")
	proto.RegisterType((*Object)(nil), "proto2.Object")
	proto.RegisterType((*ObjectCache)(nil), "proto2.ObjectCache")
	proto.RegisterType((*ObjectPath)(nil), "proto2.ObjectPath")
	proto.RegisterType((*Status)(nil), "proto2.Status")
	proto.RegisterType((*EventListenerInfo)(nil), "proto2.EventListenerInfo")
	proto.RegisterType((*AllEventListenerInfo)(nil), "proto2.AllEventListenerInfo")
	proto.RegisterType((*EventDelivererInfo)(nil), "proto2.EventDelivererInfo")
	proto.RegisterType((*ListenResult)(nil), "proto2.ListenResult")
	proto.RegisterType((*UnlistenResult)(nil), "proto2.UnlistenResult")
	proto.RegisterType((*ListenStatusChangesResult)(nil), "proto2.ListenStatusChangesResult")
	proto.RegisterType((*UnlistenStatusChangesResult)(nil), "proto2.UnlistenStatusChangesResult")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 1268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0xdf, 0x8e, 0xda, 0xc6,
	0x17, 0x5e, 0x03, 0xfb, 0x87, 0xc3, 0x9f, 0x98, 0x59, 0x96, 0x10, 0xf2, 0xd3, 0x4f, 0x5b, 0x37,
	0x8d, 0x56, 0x48, 0x4d, 0x13, 0x6f, 0x93, 0x36, 0xaa, 0x5a, 0xc9, 0xc1, 0xce, 0x2e, 0x2d, 0xc2,
	0xd4, 0x36, 0x49, 0xee, 0x2c, 0x83, 0x27, 0x40, 0xe2, 0xd8, 0xc8, 0x36, 0xac, 0x50, 0xaf, 0x72,
	0xdd, 0xeb, 0x3e, 0x4b, 0x1f, 0xa0, 0x7d, 0x99, 0xbe, 0x45, 0xe5, 0x19, 0xdb, 0xd8, 0x40, 0x89,
	0x37, 0x57, 0x8b, 0xcf, 0x39, 0xdf, 0x77, 0xce, 0xcc, 0x37, 0x73, 0xe6, 0x2c, 0x54, 0x3c, 0xec,
	0x2e, 0x67, 0x63, 0xfc, 0x68, 0xee, 0x3a, 0xbe, 0x83, 0x8e, 0xc8, 0x1f, 0x9e, 0x3b, 0x86, 0x43,
	0xe9, 0xc3, 0xdc, 0x5f, 0x71, 0x7f, 0x33, 0x00, 0x2a, 0x76, 0x97, 0xd8, 0xed, 0xda, 0x6f, 0x1d,
	0x84, 0xa0, 0x30, 0x59, 0xcc, 0xcc, 0x26, 0x73, 0xce, 0x5c, 0x14, 0x15, 0xf2, 0x1b, 0xfd, 0x00,
	0x15, 0x6f, 0x31, 0xf2, 0x56, 0x9e, 0x8f, 0x3f, 0x68, 0xab, 0x39, 0x6e, 0x16, 0xce, 0x99, 0x8b,
	0x2a, 0x7f, 0x46, 0x29, 0xf9, 0x47, 0x6a, 0xd2, 0xa9, 0xa4, 0x63, 0xd1, 0x53, 0x28, 0x85, 0x15,
	0x10, 0xe8, 0x21, 0x81, 0x9e, 0xc6, 0xd0, 0xb5, 0x4b, 0x49, 0xc6, 0xa1, 0x3a, 0x1c, 0x4e, 0x5c,
	0x67, 0x31, 0x6f, 0xe6, 0xce, 0xf3, 0x17, 0x45, 0x85, 0x7e, 0xa0, 0x26, 0x1c, 0x1b, 0xa6, 0xe9,
	0x62, 0xcf, 0x6b, 0xe6, 0x49, 0x81, 0xd1, 0x27, 0xf7, 0x91, 0x81, 0x12, 0x5d, 0xc6, 0xaf, 0x0b,
	0xec, 0xae, 0xb6, 0x6b, 0x66, 0x3e, 0xbf, 0xe6, 0x5c, 0xb6, 0x9a, 0xb9, 0x67, 0x00, 0xf2, 0xe8,
	0x1d, 0x1e, 0xfb, 0x64, 0x27, 0xab, 0x90, 0x8b, 0xf7, 0x31, 0x37, 0x33, 0x83, 0xda, 0x97, 0xd8,
	0xf5, 0x66, 0x8e, 0x4d, 0x08, 0x0b, 0x4a, 0xf4, 0xc9, 0x89, 0x70, 0x44, 0x71, 0xe8, 0x21, 0x14,
	0x66, 0xf6, 0x5b, 0x87, 0xa0, 0x4a, 0x3c, 0x8a, 0x32, 0xae, 0x59, 0x15, 0xe2, 0x0f, 0x54, 0x1a,
	0x39, 0xe6, 0x8a, 0x10, 0x95, 0x15, 0xf2, 0x9b, 0x9b, 0x40, 0x89, 0xc6, 0x75, 0x8c, 0xf1, 0x14,
	0xa3, 0x07, 0x90, 0x77, 0x46, 0xef, 0xf6, 0x30, 0x05, 0x6e, 0xc4, 0x03, 0x78, 0xb1, 0xf8, 0x84,
	0x2e, 0x11, 0xbc, 0x3e, 0x16, 0x4a, 0x22, 0x8a, 0x7b, 0x19, 0x2d, 0x73, 0x60, 0xf8, 0xd3, 0x8c,
	0x79, 0x10, 0x14, 0xe6, 0x86, 0x3f, 0x25, 0x19, 0x8a, 0x0a, 0xf9, 0xcd, 0xbd, 0x82, 0x23, 0xd5,
	0x37, 0xfc, 0x85, 0x87, 0x5a, 0x70, 0x72, 0xe3, 0xce, 0x7c, 0x63, 0x64, 0x51, 0x9d, 0x4e, 0x94,
	0xf8, 0x1b, 0x3d, 0x86, 0x13, 0x77, 0x61, 0xf7, 0xf0, 0x12, 0x5b, 0xa1, 0x10, 0xf5, 0xb8, 0x3e,
	0xa2, 0x18, 0xe5, 0x50, 0xe2, 0x28, 0xce, 0x86, 0x9a, 0xb4, 0xc4, 0xb6, 0xdf, 0x9b, 0x79, 0x3e,
	0xb6, 0xc3, 0x73, 0x9d, 0x5e, 0x28, 0x93, 0x65, 0xa1, 0xe8, 0x2b, 0x28, 0xf8, 0x6b, 0xfd, 0x6b,
	0x51, 0x34, 0x21, 0x27, 0xea, 0x13, 0x37, 0xe7, 0x42, 0x5d, 0xb0, 0xac, 0xed, 0x94, 0x97, 0x70,
	0x4c, 0xc9, 0xbc, 0x26, 0x73, 0x9e, 0xbf, 0x28, 0xf1, 0xf7, 0x52, 0x0c, 0xc9, 0x58, 0x25, 0x8a,
	0xcc, 0x9a, 0xf3, 0x1a, 0x10, 0x31, 0x89, 0xd8, 0x9a, 0x2d, 0xb1, 0xfb, 0xf9, 0x8b, 0xe4, 0x1e,
	0x40, 0x99, 0x56, 0xa2, 0x60, 0x6f, 0x61, 0xf9, 0xc1, 0xc5, 0xc3, 0xae, 0xeb, 0xb8, 0xe1, 0xc9,
	0xa5, 0x1f, 0xdc, 0x43, 0xa8, 0x0e, 0x6d, 0xeb, 0xd3, 0x71, 0x4f, 0xe0, 0x1e, 0x65, 0xa3, 0xaa,
	0x74, 0xa6, 0x86, 0x3d, 0xc1, 0xde, 0x5e, 0xc8, 0x25, 0xdc, 0x8f, 0xa8, 0x33, 0x83, 0xda, 0xbf,
	0xe7, 0xa0, 0x18, 0xef, 0x09, 0x02, 0x38, 0x92, 0x34, 0x5d, 0xe8, 0xf5, 0xd8, 0x03, 0x74, 0x06,
	0x35, 0x49, 0xd3, 0x55, 0x4d, 0xd0, 0x86, 0xaa, 0xde, 0xb9, 0x16, 0xfa, 0x57, 0x92, 0xc8, 0x02,
	0x3a, 0x85, 0x3b, 0x81, 0x59, 0x52, 0x5e, 0x49, 0x8a, 0x2e, 0x88, 0xa2, 0x24, 0xb2, 0x0c, 0x6a,
	0x00, 0x5a, 0x1b, 0x55, 0x4d, 0x1e, 0x0c, 0xba, 0xfd, 0x2b, 0x36, 0x17, 0x71, 0x24, 0xec, 0x92,
	0xc8, 0xe6, 0xd1, 0x5d, 0x38, 0x5d, 0x9b, 0x45, 0x49, 0x13, 0x3a, 0xd7, 0x41, 0x7c, 0x21, 0xcd,
	0x43, 0x1d, 0x92, 0xc8, 0x1e, 0x86, 0x3c, 0xf2, 0x8b, 0x9f, 0xa5, 0x8e, 0xa6, 0x77, 0x14, 0x49,
	0xd0, 0x24, 0x91, 0x3d, 0x4a, 0x9b, 0x45, 0xa9, 0x27, 0x05, 0xe6, 0x63, 0x74, 0x1f, 0xee, 0x26,
	0xa2, 0x03, 0x8e, 0x18, 0x73, 0xb2, 0xcb, 0x19, 0x21, 0x8b, 0xed, 0x3f, 0x19, 0x28, 0x27, 0x2f,
	0x03, 0x42, 0x50, 0x55, 0x55, 0x7d, 0xd8, 0x17, 0x5e, 0x09, 0xdd, 0x9e, 0xf0, 0xa2, 0x27, 0xb1,
	0x07, 0xc1, 0x0e, 0xa8, 0xaa, 0xde, 0xed, 0x77, 0x35, 0x7d, 0x70, 0x2d, 0xa8, 0x92, 0xfe, 0x98,
	0x6e, 0x4b, 0xda, 0xf8, 0x84, 0x2d, 0x6d, 0x1b, 0x79, 0xb6, 0x1c, 0x1a, 0xe5, 0x81, 0xa4, 0x08,
	0x5a, 0xb7, 0x7f, 0xa5, 0x2b, 0xaf, 0xd9, 0x3a, 0xba, 0x07, 0x67, 0x1b, 0x46, 0x5d, 0x93, 0x75,
	0x45, 0x66, 0xcf, 0xb6, 0xe3, 0x65, 0xb6, 0x81, 0xee, 0x40, 0x49, 0x55, 0x75, 0xf5, 0x7a, 0xa8,
	0x89, 0xf2, 0xeb, 0x3e, 0xfb, 0xff, 0xf6, 0x6f, 0xc0, 0xaa, 0x8b, 0x51, 0xd8, 0x51, 0xc3, 0xe2,
	0x49, 0x50, 0x50, 0xfd, 0x2f, 0xfd, 0x20, 0xe8, 0x20, 0x32, 0x44, 0x42, 0x30, 0x88, 0x85, 0x32,
	0x35, 0x08, 0x8a, 0x46, 0x15, 0xab, 0x41, 0x45, 0x4d, 0xa6, 0x63, 0xf3, 0xeb, 0xa0, 0x50, 0xd6,
	0x02, 0xaa, 0x02, 0x04, 0x96, 0x97, 0x42, 0xb7, 0x17, 0xc8, 0xd3, 0xfe, 0x00, 0x65, 0xda, 0xa7,
	0xc2, 0xc4, 0x55, 0x00, 0x79, 0x23, 0xaf, 0xac, 0x52, 0x0d, 0x02, 0x02, 0x26, 0x0c, 0x88, 0x44,
	0xc9, 0xa1, 0x12, 0x1c, 0xcb, 0xaa, 0xde, 0x93, 0x55, 0x8d, 0xcd, 0x87, 0xd1, 0x44, 0x94, 0x38,
	0x5d, 0x64, 0x20, 0xe9, 0xfe, 0x60, 0xa0, 0x92, 0x7a, 0x76, 0x50, 0x13, 0xea, 0x43, 0xfb, 0xbd,
	0xed, 0xdc, 0xd8, 0x29, 0x3b, 0x7b, 0x10, 0xc8, 0xdd, 0x71, 0x6c, 0xdf, 0x75, 0x2c, 0x0b, 0xbb,
	0x69, 0x27, 0x13, 0xc0, 0x54, 0xdf, 0x71, 0x8d, 0x09, 0x4e, 0x7b, 0x72, 0xc1, 0x09, 0x0d, 0x57,
	0x94, 0x72, 0xe4, 0x51, 0x0b, 0x1a, 0xea, 0x78, 0x8a, 0xcd, 0xc5, 0x16, 0x5d, 0xa1, 0xfd, 0x86,
	0xbe, 0x9c, 0xd1, 0xcb, 0xdb, 0x00, 0x14, 0x15, 0xb5, 0xb6, 0xb2, 0x07, 0x01, 0x77, 0xd4, 0xb2,
	0x92, 0x0e, 0x52, 0x4e, 0xdc, 0x86, 0x92, 0x9e, 0x1c, 0x3f, 0x80, 0x6a, 0xba, 0x4b, 0xa1, 0x9f,
	0xe0, 0x8e, 0x6c, 0x53, 0x1a, 0x7a, 0xcd, 0x4d, 0xf4, 0xbf, 0xa8, 0x41, 0xed, 0x6a, 0xa2, 0xad,
	0x4a, 0xdc, 0x01, 0x83, 0x69, 0x85, 0xff, 0x58, 0x80, 0x4a, 0x2a, 0x08, 0xf1, 0x50, 0x91, 0x6d,
	0xda, 0xdb, 0x04, 0xd3, 0xc4, 0x26, 0xda, 0xd1, 0xf0, 0x36, 0x58, 0xd0, 0x53, 0x60, 0x23, 0x8c,
	0xea, 0x3b, 0xf3, 0xf9, 0xcc, 0x9e, 0x64, 0x81, 0x7d, 0x1b, 0x14, 0x9f, 0x80, 0x65, 0x4b, 0xf6,
	0x0c, 0x6a, 0x11, 0x4a, 0xc4, 0xbe, 0x31, 0x9e, 0x66, 0xcc, 0x96, 0x28, 0x92, 0xe2, 0xb2, 0xa5,
	0x23, 0x45, 0x86, 0x83, 0x80, 0x8b, 0x0d, 0x3f, 0x89, 0x5a, 0xbf, 0xca, 0x7b, 0x50, 0x22, 0xb6,
	0x70, 0x46, 0xd4, 0x73, 0xa8, 0xc7, 0xb9, 0x82, 0x02, 0x6f, 0x91, 0x70, 0x13, 0x9a, 0x3d, 0x2b,
	0xff, 0x57, 0x01, 0x6a, 0x89, 0xcb, 0x41, 0x4f, 0x1c, 0x6a, 0x03, 0x04, 0xa2, 0xd0, 0x36, 0x88,
	0xd2, 0x90, 0xcd, 0xe4, 0x3c, 0x54, 0x04, 0xd3, 0x4c, 0x4e, 0xbd, 0x9f, 0xde, 0xd7, 0x4b, 0xa8,
	0x12, 0xfe, 0x5b, 0x81, 0x9e, 0x02, 0x4b, 0xb5, 0xbb, 0x1d, 0xec, 0x7b, 0xa8, 0x5c, 0x61, 0x3f,
	0x81, 0x39, 0x4d, 0x63, 0xc8, 0x88, 0xdb, 0xda, 0x41, 0x84, 0x9e, 0xc3, 0x11, 0xbd, 0x19, 0xe8,
	0xbf, 0x87, 0x8d, 0x56, 0x3c, 0x40, 0xa5, 0x1e, 0xfe, 0x1f, 0xe1, 0x24, 0x7a, 0x87, 0xf7, 0x81,
	0x1b, 0x91, 0x6b, 0x63, 0x1e, 0xd0, 0xa2, 0xf6, 0x90, 0x7a, 0xc4, 0x51, 0x2b, 0xc5, 0x94, 0x1a,
	0x57, 0x5a, 0x5f, 0xa4, 0xeb, 0xd8, 0xf5, 0xfa, 0xbf, 0x81, 0xb3, 0x9d, 0xc3, 0xc1, 0x5e, 0xde,
	0x2f, 0x37, 0x4b, 0xdc, 0xc1, 0xcc, 0xbb, 0x44, 0x4f, 0xd2, 0x44, 0xc3, 0x13, 0xf4, 0x35, 0x94,
	0xe9, 0x01, 0x0e, 0x87, 0xf1, 0x6a, 0xfa, 0x28, 0x6e, 0x8a, 0xf4, 0x04, 0xca, 0xf4, 0xd0, 0x86,
	0xe1, 0x19, 0x4e, 0xee, 0x3f, 0x0c, 0x9c, 0xf6, 0x9c, 0xb1, 0x61, 0x6d, 0x64, 0xfe, 0x0e, 0x50,
	0x32, 0xf3, 0x8b, 0x15, 0x99, 0xac, 0x37, 0x08, 0x03, 0xdb, 0x8e, 0x43, 0x29, 0x3a, 0x37, 0xb6,
	0xe5, 0x18, 0x66, 0xe6, 0x2a, 0xd0, 0x63, 0x28, 0x29, 0x3d, 0x67, 0xfc, 0x3e, 0x3b, 0x82, 0x87,
	0x8a, 0x32, 0xb4, 0xad, 0xdb, 0x60, 0xf8, 0x05, 0x34, 0xba, 0xb6, 0x8f, 0x5d, 0x7b, 0x6b, 0xb5,
	0xdf, 0x40, 0xf1, 0x0a, 0xfb, 0x7b, 0x98, 0x36, 0x36, 0x1e, 0xb5, 0xa1, 0x38, 0x58, 0xf8, 0x99,
	0x54, 0x19, 0xd1, 0xff, 0x6f, 0x2f, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x78, 0x40, 0xd1, 0x9a,
	0xf7, 0x0e, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EventDelivererClient is the client API for EventDeliverer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventDelivererClient interface {
	// listen状態が変化したときに呼び出される。
	// [Manager] --> [Deliverer]
	OnListenChanged(ctx context.Context, in *AllEventListenerInfo, opts ...grpc.CallOption) (*Empty, error)
}

type eventDelivererClient struct {
	cc *grpc.ClientConn
}

func NewEventDelivererClient(cc *grpc.ClientConn) EventDelivererClient {
	return &eventDelivererClient{cc}
}

func (c *eventDelivererClient) OnListenChanged(ctx context.Context, in *AllEventListenerInfo, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto2.EventDeliverer/OnListenChanged", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventDelivererServer is the server API for EventDeliverer service.
type EventDelivererServer interface {
	// listen状態が変化したときに呼び出される。
	// [Manager] --> [Deliverer]
	OnListenChanged(context.Context, *AllEventListenerInfo) (*Empty, error)
}

func RegisterEventDelivererServer(s *grpc.Server, srv EventDelivererServer) {
	s.RegisterService(&_EventDeliverer_serviceDesc, srv)
}

func _EventDeliverer_OnListenChanged_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllEventListenerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventDelivererServer).OnListenChanged(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto2.EventDeliverer/OnListenChanged",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventDelivererServer).OnListenChanged(ctx, req.(*AllEventListenerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _EventDeliverer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto2.EventDeliverer",
	HandlerType: (*EventDelivererServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnListenChanged",
			Handler:    _EventDeliverer_OnListenChanged_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

// EventListenerClient is the client API for EventListener service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventListenerClient interface {
	// イベントが発生したときに呼び出される。
	// [Deliverer] --> [Listener]
	OnServerAdded(ctx context.Context, in *ServerInfo, opts ...grpc.CallOption) (*Empty, error)
	OnServerStopping(ctx context.Context, in *ServerInfo, opts ...grpc.CallOption) (*Empty, error)
	OnServerStopped(ctx context.Context, in *ServerInfo, opts ...grpc.CallOption) (*Empty, error)
	OnServerDetaching(ctx context.Context, in *ServerInfo, opts ...grpc.CallOption) (*Empty, error)
	OnServerDetached(ctx context.Context, in *ServerInfo, opts ...grpc.CallOption) (*Empty, error)
	OnObjectCreated(ctx context.Context, in *ObjectInfo, opts ...grpc.CallOption) (*Empty, error)
	OnObjectDeleted(ctx context.Context, in *ObjectInfo, opts ...grpc.CallOption) (*Empty, error)
	OnObjectCacheCreated(ctx context.Context, in *ObjectInfo, opts ...grpc.CallOption) (*Empty, error)
	OnObjectCacheDeleted(ctx context.Context, in *ObjectInfo, opts ...grpc.CallOption) (*Empty, error)
}

type eventListenerClient struct {
	cc *grpc.ClientConn
}

func NewEventListenerClient(cc *grpc.ClientConn) EventListenerClient {
	return &eventListenerClient{cc}
}

func (c *eventListenerClient) OnServerAdded(ctx context.Context, in *ServerInfo, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto2.EventListener/OnServerAdded", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventListenerClient) OnServerStopping(ctx context.Context, in *ServerInfo, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto2.EventListener/OnServerStopping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventListenerClient) OnServerStopped(ctx context.Context, in *ServerInfo, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto2.EventListener/OnServerStopped", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventListenerClient) OnServerDetaching(ctx context.Context, in *ServerInfo, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto2.EventListener/OnServerDetaching", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventListenerClient) OnServerDetached(ctx context.Context, in *ServerInfo, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto2.EventListener/OnServerDetached", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventListenerClient) OnObjectCreated(ctx context.Context, in *ObjectInfo, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto2.EventListener/OnObjectCreated", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventListenerClient) OnObjectDeleted(ctx context.Context, in *ObjectInfo, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto2.EventListener/OnObjectDeleted", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventListenerClient) OnObjectCacheCreated(ctx context.Context, in *ObjectInfo, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto2.EventListener/OnObjectCacheCreated", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventListenerClient) OnObjectCacheDeleted(ctx context.Context, in *ObjectInfo, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto2.EventListener/OnObjectCacheDeleted", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventListenerServer is the server API for EventListener service.
type EventListenerServer interface {
	// イベントが発生したときに呼び出される。
	// [Deliverer] --> [Listener]
	OnServerAdded(context.Context, *ServerInfo) (*Empty, error)
	OnServerStopping(context.Context, *ServerInfo) (*Empty, error)
	OnServerStopped(context.Context, *ServerInfo) (*Empty, error)
	OnServerDetaching(context.Context, *ServerInfo) (*Empty, error)
	OnServerDetached(context.Context, *ServerInfo) (*Empty, error)
	OnObjectCreated(context.Context, *ObjectInfo) (*Empty, error)
	OnObjectDeleted(context.Context, *ObjectInfo) (*Empty, error)
	OnObjectCacheCreated(context.Context, *ObjectInfo) (*Empty, error)
	OnObjectCacheDeleted(context.Context, *ObjectInfo) (*Empty, error)
}

func RegisterEventListenerServer(s *grpc.Server, srv EventListenerServer) {
	s.RegisterService(&_EventListener_serviceDesc, srv)
}

func _EventListener_OnServerAdded_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventListenerServer).OnServerAdded(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto2.EventListener/OnServerAdded",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventListenerServer).OnServerAdded(ctx, req.(*ServerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventListener_OnServerStopping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventListenerServer).OnServerStopping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto2.EventListener/OnServerStopping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventListenerServer).OnServerStopping(ctx, req.(*ServerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventListener_OnServerStopped_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventListenerServer).OnServerStopped(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto2.EventListener/OnServerStopped",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventListenerServer).OnServerStopped(ctx, req.(*ServerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventListener_OnServerDetaching_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventListenerServer).OnServerDetaching(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto2.EventListener/OnServerDetaching",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventListenerServer).OnServerDetaching(ctx, req.(*ServerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventListener_OnServerDetached_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventListenerServer).OnServerDetached(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto2.EventListener/OnServerDetached",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventListenerServer).OnServerDetached(ctx, req.(*ServerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventListener_OnObjectCreated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventListenerServer).OnObjectCreated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto2.EventListener/OnObjectCreated",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventListenerServer).OnObjectCreated(ctx, req.(*ObjectInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventListener_OnObjectDeleted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventListenerServer).OnObjectDeleted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto2.EventListener/OnObjectDeleted",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventListenerServer).OnObjectDeleted(ctx, req.(*ObjectInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventListener_OnObjectCacheCreated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventListenerServer).OnObjectCacheCreated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto2.EventListener/OnObjectCacheCreated",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventListenerServer).OnObjectCacheCreated(ctx, req.(*ObjectInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventListener_OnObjectCacheDeleted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventListenerServer).OnObjectCacheDeleted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto2.EventListener/OnObjectCacheDeleted",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventListenerServer).OnObjectCacheDeleted(ctx, req.(*ObjectInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _EventListener_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto2.EventListener",
	HandlerType: (*EventListenerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnServerAdded",
			Handler:    _EventListener_OnServerAdded_Handler,
		},
		{
			MethodName: "OnServerStopping",
			Handler:    _EventListener_OnServerStopping_Handler,
		},
		{
			MethodName: "OnServerStopped",
			Handler:    _EventListener_OnServerStopped_Handler,
		},
		{
			MethodName: "OnServerDetaching",
			Handler:    _EventListener_OnServerDetaching_Handler,
		},
		{
			MethodName: "OnServerDetached",
			Handler:    _EventListener_OnServerDetached_Handler,
		},
		{
			MethodName: "OnObjectCreated",
			Handler:    _EventListener_OnObjectCreated_Handler,
		},
		{
			MethodName: "OnObjectDeleted",
			Handler:    _EventListener_OnObjectDeleted_Handler,
		},
		{
			MethodName: "OnObjectCacheCreated",
			Handler:    _EventListener_OnObjectCacheCreated_Handler,
		},
		{
			MethodName: "OnObjectCacheDeleted",
			Handler:    _EventListener_OnObjectCacheDeleted_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

// ControllerServiceClient is the client API for ControllerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ControllerServiceClient interface {
	// Eltonシステムを停止する。
	StopSystem(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	AddServerInfo(ctx context.Context, in *ServerInfo, opts ...grpc.CallOption) (*Empty, error)
	StopServerInfo(ctx context.Context, in *ServerInfo, opts ...grpc.CallOption) (*Empty, error)
	DetachServerInfo(ctx context.Context, in *ServerInfo, opts ...grpc.CallOption) (*Empty, error)
	GetServerInfo(ctx context.Context, in *ServerQuery, opts ...grpc.CallOption) (*ServerInfo, error)
	// 指定したイベントをlistenする。
	// [Listener] --> [Manager]
	Listen(ctx context.Context, in *EventListenerInfo, opts ...grpc.CallOption) (*ListenResult, error)
	// 指定したイベントをunlistenする。
	// [Listener] --> [Manager]
	Unlisten(ctx context.Context, in *EventListenerInfo, opts ...grpc.CallOption) (*UnlistenResult, error)
	// Listen状態の変化をlistenする。
	// [Deliverer] --> [Manager]
	ListenStatusChanges(ctx context.Context, in *EventDelivererInfo, opts ...grpc.CallOption) (*ListenStatusChangesResult, error)
	// Listen状態の変化をunlistenする。
	// [Deliverer] --> [Manager]
	UnlistenStatusChanges(ctx context.Context, in *EventDelivererInfo, opts ...grpc.CallOption) (*UnlistenStatusChangesResult, error)
}

type controllerServiceClient struct {
	cc *grpc.ClientConn
}

func NewControllerServiceClient(cc *grpc.ClientConn) ControllerServiceClient {
	return &controllerServiceClient{cc}
}

func (c *controllerServiceClient) StopSystem(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto2.ControllerService/StopSystem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) AddServerInfo(ctx context.Context, in *ServerInfo, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto2.ControllerService/AddServerInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) StopServerInfo(ctx context.Context, in *ServerInfo, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto2.ControllerService/StopServerInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) DetachServerInfo(ctx context.Context, in *ServerInfo, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto2.ControllerService/DetachServerInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) GetServerInfo(ctx context.Context, in *ServerQuery, opts ...grpc.CallOption) (*ServerInfo, error) {
	out := new(ServerInfo)
	err := c.cc.Invoke(ctx, "/proto2.ControllerService/GetServerInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) Listen(ctx context.Context, in *EventListenerInfo, opts ...grpc.CallOption) (*ListenResult, error) {
	out := new(ListenResult)
	err := c.cc.Invoke(ctx, "/proto2.ControllerService/Listen", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) Unlisten(ctx context.Context, in *EventListenerInfo, opts ...grpc.CallOption) (*UnlistenResult, error) {
	out := new(UnlistenResult)
	err := c.cc.Invoke(ctx, "/proto2.ControllerService/Unlisten", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) ListenStatusChanges(ctx context.Context, in *EventDelivererInfo, opts ...grpc.CallOption) (*ListenStatusChangesResult, error) {
	out := new(ListenStatusChangesResult)
	err := c.cc.Invoke(ctx, "/proto2.ControllerService/ListenStatusChanges", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) UnlistenStatusChanges(ctx context.Context, in *EventDelivererInfo, opts ...grpc.CallOption) (*UnlistenStatusChangesResult, error) {
	out := new(UnlistenStatusChangesResult)
	err := c.cc.Invoke(ctx, "/proto2.ControllerService/UnlistenStatusChanges", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControllerServiceServer is the server API for ControllerService service.
type ControllerServiceServer interface {
	// Eltonシステムを停止する。
	StopSystem(context.Context, *Empty) (*Empty, error)
	AddServerInfo(context.Context, *ServerInfo) (*Empty, error)
	StopServerInfo(context.Context, *ServerInfo) (*Empty, error)
	DetachServerInfo(context.Context, *ServerInfo) (*Empty, error)
	GetServerInfo(context.Context, *ServerQuery) (*ServerInfo, error)
	// 指定したイベントをlistenする。
	// [Listener] --> [Manager]
	Listen(context.Context, *EventListenerInfo) (*ListenResult, error)
	// 指定したイベントをunlistenする。
	// [Listener] --> [Manager]
	Unlisten(context.Context, *EventListenerInfo) (*UnlistenResult, error)
	// Listen状態の変化をlistenする。
	// [Deliverer] --> [Manager]
	ListenStatusChanges(context.Context, *EventDelivererInfo) (*ListenStatusChangesResult, error)
	// Listen状態の変化をunlistenする。
	// [Deliverer] --> [Manager]
	UnlistenStatusChanges(context.Context, *EventDelivererInfo) (*UnlistenStatusChangesResult, error)
}

func RegisterControllerServiceServer(s *grpc.Server, srv ControllerServiceServer) {
	s.RegisterService(&_ControllerService_serviceDesc, srv)
}

func _ControllerService_StopSystem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).StopSystem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto2.ControllerService/StopSystem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).StopSystem(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_AddServerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).AddServerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto2.ControllerService/AddServerInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).AddServerInfo(ctx, req.(*ServerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_StopServerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).StopServerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto2.ControllerService/StopServerInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).StopServerInfo(ctx, req.(*ServerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_DetachServerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).DetachServerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto2.ControllerService/DetachServerInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).DetachServerInfo(ctx, req.(*ServerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_GetServerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).GetServerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto2.ControllerService/GetServerInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).GetServerInfo(ctx, req.(*ServerQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_Listen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventListenerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).Listen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto2.ControllerService/Listen",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).Listen(ctx, req.(*EventListenerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_Unlisten_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventListenerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).Unlisten(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto2.ControllerService/Unlisten",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).Unlisten(ctx, req.(*EventListenerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_ListenStatusChanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventDelivererInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).ListenStatusChanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto2.ControllerService/ListenStatusChanges",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).ListenStatusChanges(ctx, req.(*EventDelivererInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_UnlistenStatusChanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventDelivererInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).UnlistenStatusChanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto2.ControllerService/UnlistenStatusChanges",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).UnlistenStatusChanges(ctx, req.(*EventDelivererInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _ControllerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto2.ControllerService",
	HandlerType: (*ControllerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StopSystem",
			Handler:    _ControllerService_StopSystem_Handler,
		},
		{
			MethodName: "AddServerInfo",
			Handler:    _ControllerService_AddServerInfo_Handler,
		},
		{
			MethodName: "StopServerInfo",
			Handler:    _ControllerService_StopServerInfo_Handler,
		},
		{
			MethodName: "DetachServerInfo",
			Handler:    _ControllerService_DetachServerInfo_Handler,
		},
		{
			MethodName: "GetServerInfo",
			Handler:    _ControllerService_GetServerInfo_Handler,
		},
		{
			MethodName: "Listen",
			Handler:    _ControllerService_Listen_Handler,
		},
		{
			MethodName: "Unlisten",
			Handler:    _ControllerService_Unlisten_Handler,
		},
		{
			MethodName: "ListenStatusChanges",
			Handler:    _ControllerService_ListenStatusChanges_Handler,
		},
		{
			MethodName: "UnlistenStatusChanges",
			Handler:    _ControllerService_UnlistenStatusChanges_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

// StorageServiceClient is the client API for StorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StorageServiceClient interface {
	CreateObject(ctx context.Context, in *Object, opts ...grpc.CallOption) (*Empty, error)
	DeleteObject(ctx context.Context, in *ObjectInfo, opts ...grpc.CallOption) (*Empty, error)
}

type storageServiceClient struct {
	cc *grpc.ClientConn
}

func NewStorageServiceClient(cc *grpc.ClientConn) StorageServiceClient {
	return &storageServiceClient{cc}
}

func (c *storageServiceClient) CreateObject(ctx context.Context, in *Object, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto2.StorageService/CreateObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) DeleteObject(ctx context.Context, in *ObjectInfo, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto2.StorageService/DeleteObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServiceServer is the server API for StorageService service.
type StorageServiceServer interface {
	CreateObject(context.Context, *Object) (*Empty, error)
	DeleteObject(context.Context, *ObjectInfo) (*Empty, error)
}

func RegisterStorageServiceServer(s *grpc.Server, srv StorageServiceServer) {
	s.RegisterService(&_StorageService_serviceDesc, srv)
}

func _StorageService_CreateObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Object)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).CreateObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto2.StorageService/CreateObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).CreateObject(ctx, req.(*Object))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_DeleteObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).DeleteObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto2.StorageService/DeleteObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).DeleteObject(ctx, req.(*ObjectInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _StorageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto2.StorageService",
	HandlerType: (*StorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateObject",
			Handler:    _StorageService_CreateObject_Handler,
		},
		{
			MethodName: "DeleteObject",
			Handler:    _StorageService_DeleteObject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

// LocalStorageServiceClient is the client API for LocalStorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LocalStorageServiceClient interface {
	CreateObjectByPath(ctx context.Context, in *ObjectPath, opts ...grpc.CallOption) (*Empty, error)
	DownloadObject(ctx context.Context, in *ObjectInfo, opts ...grpc.CallOption) (*Empty, error)
	RLockObject(ctx context.Context, in *ObjectInfo, opts ...grpc.CallOption) (*Empty, error)
	RUnlockObject(ctx context.Context, in *ObjectInfo, opts ...grpc.CallOption) (*Empty, error)
}

type localStorageServiceClient struct {
	cc *grpc.ClientConn
}

func NewLocalStorageServiceClient(cc *grpc.ClientConn) LocalStorageServiceClient {
	return &localStorageServiceClient{cc}
}

func (c *localStorageServiceClient) CreateObjectByPath(ctx context.Context, in *ObjectPath, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto2.LocalStorageService/CreateObjectByPath", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localStorageServiceClient) DownloadObject(ctx context.Context, in *ObjectInfo, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto2.LocalStorageService/DownloadObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localStorageServiceClient) RLockObject(ctx context.Context, in *ObjectInfo, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto2.LocalStorageService/RLockObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localStorageServiceClient) RUnlockObject(ctx context.Context, in *ObjectInfo, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto2.LocalStorageService/RUnlockObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LocalStorageServiceServer is the server API for LocalStorageService service.
type LocalStorageServiceServer interface {
	CreateObjectByPath(context.Context, *ObjectPath) (*Empty, error)
	DownloadObject(context.Context, *ObjectInfo) (*Empty, error)
	RLockObject(context.Context, *ObjectInfo) (*Empty, error)
	RUnlockObject(context.Context, *ObjectInfo) (*Empty, error)
}

func RegisterLocalStorageServiceServer(s *grpc.Server, srv LocalStorageServiceServer) {
	s.RegisterService(&_LocalStorageService_serviceDesc, srv)
}

func _LocalStorageService_CreateObjectByPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectPath)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalStorageServiceServer).CreateObjectByPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto2.LocalStorageService/CreateObjectByPath",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalStorageServiceServer).CreateObjectByPath(ctx, req.(*ObjectPath))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalStorageService_DownloadObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalStorageServiceServer).DownloadObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto2.LocalStorageService/DownloadObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalStorageServiceServer).DownloadObject(ctx, req.(*ObjectInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalStorageService_RLockObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalStorageServiceServer).RLockObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto2.LocalStorageService/RLockObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalStorageServiceServer).RLockObject(ctx, req.(*ObjectInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalStorageService_RUnlockObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalStorageServiceServer).RUnlockObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto2.LocalStorageService/RUnlockObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalStorageServiceServer).RUnlockObject(ctx, req.(*ObjectInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _LocalStorageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto2.LocalStorageService",
	HandlerType: (*LocalStorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateObjectByPath",
			Handler:    _LocalStorageService_CreateObjectByPath_Handler,
		},
		{
			MethodName: "DownloadObject",
			Handler:    _LocalStorageService_DownloadObject_Handler,
		},
		{
			MethodName: "RLockObject",
			Handler:    _LocalStorageService_RLockObject_Handler,
		},
		{
			MethodName: "RUnlockObject",
			Handler:    _LocalStorageService_RUnlockObject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

// InternalStorageServiceClient is the client API for InternalStorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InternalStorageServiceClient interface {
	// TODO
	GetObject(ctx context.Context, in *ObjectInfo, opts ...grpc.CallOption) (*Object, error)
	PutObject(ctx context.Context, in *Object, opts ...grpc.CallOption) (*Empty, error)
}

type internalStorageServiceClient struct {
	cc *grpc.ClientConn
}

func NewInternalStorageServiceClient(cc *grpc.ClientConn) InternalStorageServiceClient {
	return &internalStorageServiceClient{cc}
}

func (c *internalStorageServiceClient) GetObject(ctx context.Context, in *ObjectInfo, opts ...grpc.CallOption) (*Object, error) {
	out := new(Object)
	err := c.cc.Invoke(ctx, "/proto2.InternalStorageService/GetObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalStorageServiceClient) PutObject(ctx context.Context, in *Object, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto2.InternalStorageService/PutObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalStorageServiceServer is the server API for InternalStorageService service.
type InternalStorageServiceServer interface {
	// TODO
	GetObject(context.Context, *ObjectInfo) (*Object, error)
	PutObject(context.Context, *Object) (*Empty, error)
}

func RegisterInternalStorageServiceServer(s *grpc.Server, srv InternalStorageServiceServer) {
	s.RegisterService(&_InternalStorageService_serviceDesc, srv)
}

func _InternalStorageService_GetObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalStorageServiceServer).GetObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto2.InternalStorageService/GetObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalStorageServiceServer).GetObject(ctx, req.(*ObjectInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalStorageService_PutObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Object)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalStorageServiceServer).PutObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto2.InternalStorageService/PutObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalStorageServiceServer).PutObject(ctx, req.(*Object))
	}
	return interceptor(ctx, in, info, handler)
}

var _InternalStorageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto2.InternalStorageService",
	HandlerType: (*InternalStorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetObject",
			Handler:    _InternalStorageService_GetObject_Handler,
		},
		{
			MethodName: "PutObject",
			Handler:    _InternalStorageService_PutObject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
