// Code generated by protoc-gen-go. DO NOT EDIT.
// source: node.proto

package elton_v2

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterNodeRequest struct {
	Id                   *NodeID  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Node                 *Node    `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterNodeRequest) Reset()         { *m = RegisterNodeRequest{} }
func (m *RegisterNodeRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterNodeRequest) ProtoMessage()    {}
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{0}
}

func (m *RegisterNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterNodeRequest.Unmarshal(m, b)
}
func (m *RegisterNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterNodeRequest.Marshal(b, m, deterministic)
}
func (m *RegisterNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterNodeRequest.Merge(m, src)
}
func (m *RegisterNodeRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterNodeRequest.Size(m)
}
func (m *RegisterNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterNodeRequest proto.InternalMessageInfo

func (m *RegisterNodeRequest) GetId() *NodeID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *RegisterNodeRequest) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type RegisterNodeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterNodeResponse) Reset()         { *m = RegisterNodeResponse{} }
func (m *RegisterNodeResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterNodeResponse) ProtoMessage()    {}
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{1}
}

func (m *RegisterNodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterNodeResponse.Unmarshal(m, b)
}
func (m *RegisterNodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterNodeResponse.Marshal(b, m, deterministic)
}
func (m *RegisterNodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterNodeResponse.Merge(m, src)
}
func (m *RegisterNodeResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterNodeResponse.Size(m)
}
func (m *RegisterNodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterNodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterNodeResponse proto.InternalMessageInfo

type UnregisterNodeRequest struct {
	Id                   *NodeID  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnregisterNodeRequest) Reset()         { *m = UnregisterNodeRequest{} }
func (m *UnregisterNodeRequest) String() string { return proto.CompactTextString(m) }
func (*UnregisterNodeRequest) ProtoMessage()    {}
func (*UnregisterNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{2}
}

func (m *UnregisterNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnregisterNodeRequest.Unmarshal(m, b)
}
func (m *UnregisterNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnregisterNodeRequest.Marshal(b, m, deterministic)
}
func (m *UnregisterNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnregisterNodeRequest.Merge(m, src)
}
func (m *UnregisterNodeRequest) XXX_Size() int {
	return xxx_messageInfo_UnregisterNodeRequest.Size(m)
}
func (m *UnregisterNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnregisterNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnregisterNodeRequest proto.InternalMessageInfo

func (m *UnregisterNodeRequest) GetId() *NodeID {
	if m != nil {
		return m.Id
	}
	return nil
}

type UnregisterNodeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnregisterNodeResponse) Reset()         { *m = UnregisterNodeResponse{} }
func (m *UnregisterNodeResponse) String() string { return proto.CompactTextString(m) }
func (*UnregisterNodeResponse) ProtoMessage()    {}
func (*UnregisterNodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{3}
}

func (m *UnregisterNodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnregisterNodeResponse.Unmarshal(m, b)
}
func (m *UnregisterNodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnregisterNodeResponse.Marshal(b, m, deterministic)
}
func (m *UnregisterNodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnregisterNodeResponse.Merge(m, src)
}
func (m *UnregisterNodeResponse) XXX_Size() int {
	return xxx_messageInfo_UnregisterNodeResponse.Size(m)
}
func (m *UnregisterNodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnregisterNodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnregisterNodeResponse proto.InternalMessageInfo

type PingNodeRequest struct {
	Id                   *NodeID  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingNodeRequest) Reset()         { *m = PingNodeRequest{} }
func (m *PingNodeRequest) String() string { return proto.CompactTextString(m) }
func (*PingNodeRequest) ProtoMessage()    {}
func (*PingNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{4}
}

func (m *PingNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingNodeRequest.Unmarshal(m, b)
}
func (m *PingNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingNodeRequest.Marshal(b, m, deterministic)
}
func (m *PingNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingNodeRequest.Merge(m, src)
}
func (m *PingNodeRequest) XXX_Size() int {
	return xxx_messageInfo_PingNodeRequest.Size(m)
}
func (m *PingNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingNodeRequest proto.InternalMessageInfo

func (m *PingNodeRequest) GetId() *NodeID {
	if m != nil {
		return m.Id
	}
	return nil
}

type PingNodeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingNodeResponse) Reset()         { *m = PingNodeResponse{} }
func (m *PingNodeResponse) String() string { return proto.CompactTextString(m) }
func (*PingNodeResponse) ProtoMessage()    {}
func (*PingNodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{5}
}

func (m *PingNodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingNodeResponse.Unmarshal(m, b)
}
func (m *PingNodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingNodeResponse.Marshal(b, m, deterministic)
}
func (m *PingNodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingNodeResponse.Merge(m, src)
}
func (m *PingNodeResponse) XXX_Size() int {
	return xxx_messageInfo_PingNodeResponse.Size(m)
}
func (m *PingNodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingNodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingNodeResponse proto.InternalMessageInfo

type ListNodesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListNodesRequest) Reset()         { *m = ListNodesRequest{} }
func (m *ListNodesRequest) String() string { return proto.CompactTextString(m) }
func (*ListNodesRequest) ProtoMessage()    {}
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{6}
}

func (m *ListNodesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNodesRequest.Unmarshal(m, b)
}
func (m *ListNodesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNodesRequest.Marshal(b, m, deterministic)
}
func (m *ListNodesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNodesRequest.Merge(m, src)
}
func (m *ListNodesRequest) XXX_Size() int {
	return xxx_messageInfo_ListNodesRequest.Size(m)
}
func (m *ListNodesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNodesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListNodesRequest proto.InternalMessageInfo

type ListNodesResponse struct {
	Id                   *NodeID  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nodes                *Node    `protobuf:"bytes,2,opt,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListNodesResponse) Reset()         { *m = ListNodesResponse{} }
func (m *ListNodesResponse) String() string { return proto.CompactTextString(m) }
func (*ListNodesResponse) ProtoMessage()    {}
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{7}
}

func (m *ListNodesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNodesResponse.Unmarshal(m, b)
}
func (m *ListNodesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNodesResponse.Marshal(b, m, deterministic)
}
func (m *ListNodesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNodesResponse.Merge(m, src)
}
func (m *ListNodesResponse) XXX_Size() int {
	return xxx_messageInfo_ListNodesResponse.Size(m)
}
func (m *ListNodesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNodesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListNodesResponse proto.InternalMessageInfo

func (m *ListNodesResponse) GetId() *NodeID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ListNodesResponse) GetNodes() *Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func init() {
	proto.RegisterType((*RegisterNodeRequest)(nil), "elton.v2.RegisterNodeRequest")
	proto.RegisterType((*RegisterNodeResponse)(nil), "elton.v2.RegisterNodeResponse")
	proto.RegisterType((*UnregisterNodeRequest)(nil), "elton.v2.UnregisterNodeRequest")
	proto.RegisterType((*UnregisterNodeResponse)(nil), "elton.v2.UnregisterNodeResponse")
	proto.RegisterType((*PingNodeRequest)(nil), "elton.v2.PingNodeRequest")
	proto.RegisterType((*PingNodeResponse)(nil), "elton.v2.PingNodeResponse")
	proto.RegisterType((*ListNodesRequest)(nil), "elton.v2.ListNodesRequest")
	proto.RegisterType((*ListNodesResponse)(nil), "elton.v2.ListNodesResponse")
}

func init() { proto.RegisterFile("node.proto", fileDescriptor_0c843d59d2d938e7) }

var fileDescriptor_0c843d59d2d938e7 = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x4d, 0x4b, 0xf4, 0x30,
	0x10, 0xc7, 0x69, 0xd9, 0xe7, 0x41, 0xa7, 0xb2, 0xd6, 0x51, 0x97, 0x1a, 0x51, 0x4b, 0xf0, 0xe0,
	0xa9, 0x48, 0xf7, 0xe4, 0xc1, 0x9b, 0x08, 0x82, 0x8a, 0x74, 0xf1, 0xb4, 0x37, 0xed, 0xb0, 0x04,
	0x24, 0xa9, 0x4d, 0x5c, 0xf0, 0x9b, 0xf9, 0xf1, 0x24, 0x6d, 0xb4, 0x2f, 0xb4, 0xa0, 0x1e, 0x33,
	0xff, 0x97, 0x84, 0xdf, 0x04, 0x40, 0xaa, 0x9c, 0x92, 0xa2, 0x54, 0x46, 0xe1, 0x06, 0xbd, 0x18,
	0x25, 0x93, 0x75, 0xca, 0x02, 0xf3, 0x5e, 0x90, 0xae, 0xc7, 0x7c, 0x09, 0xbb, 0x19, 0xad, 0x84,
	0x36, 0x54, 0xde, 0xab, 0x9c, 0x32, 0x7a, 0x7d, 0x23, 0x6d, 0x30, 0x06, 0x5f, 0xe4, 0x91, 0x17,
	0x7b, 0x67, 0x41, 0x1a, 0x26, 0x5f, 0xd1, 0xc4, 0x5a, 0x6e, 0xae, 0x32, 0x5f, 0xe4, 0xc8, 0x61,
	0x62, 0xdb, 0x23, 0xbf, 0xf2, 0x4c, 0xbb, 0x9e, 0xac, 0xd2, 0xf8, 0x0c, 0xf6, 0xba, 0xe5, 0xba,
	0x50, 0x52, 0x13, 0xbf, 0x80, 0xfd, 0x47, 0x59, 0xfe, 0xe5, 0x5a, 0x1e, 0xc1, 0xac, 0x1f, 0x75,
	0xa5, 0x73, 0xd8, 0x7e, 0x10, 0x72, 0xf5, 0xbb, 0x3a, 0x84, 0xb0, 0x09, 0xb9, 0x22, 0x84, 0xf0,
	0x56, 0x68, 0x63, 0x67, 0xda, 0x35, 0xf1, 0x25, 0xec, 0xb4, 0x66, 0xb5, 0xf1, 0x07, 0x90, 0x4e,
	0xe1, 0x9f, 0x05, 0xa1, 0x47, 0x28, 0xd5, 0x62, 0xfa, 0xe1, 0x43, 0x60, 0xcf, 0x0b, 0x2a, 0xd7,
	0xe2, 0x99, 0xf0, 0x0e, 0xb6, 0xda, 0xd8, 0xf0, 0xa8, 0x89, 0x0d, 0xec, 0x8a, 0x1d, 0x8f, 0xc9,
	0xee, 0x99, 0x0b, 0x98, 0x76, 0x91, 0xe1, 0x49, 0x93, 0x18, 0xdc, 0x03, 0x8b, 0xc7, 0x0d, 0xae,
	0xf4, 0x12, 0x26, 0x16, 0x1c, 0x1e, 0x34, 0xce, 0x1e, 0x7d, 0xc6, 0x86, 0x24, 0x17, 0xbf, 0x86,
	0xcd, 0x6f, 0x9e, 0xd8, 0x32, 0xf6, 0xc1, 0xb3, 0xc3, 0x41, 0xad, 0x6e, 0x39, 0xf7, 0x9e, 0xfe,
	0x57, 0xbf, 0x78, 0xfe, 0x19, 0x00, 0x00, 0xff, 0xff, 0x7b, 0xdd, 0x4a, 0xd0, 0xea, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NodeServiceClient is the client API for NodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NodeServiceClient interface {
	// クラスタに参加するときや、ノードの構成変更をしたときに呼び出すAPI。
	// ノードの情報を登録・更新をする。
	RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error)
	// クラスタから脱退するときに呼び出すAPI。
	// ノードの退避処理を行い、ノードの情報を削除する。
	UnregisterNode(ctx context.Context, in *UnregisterNodeRequest, opts ...grpc.CallOption) (*UnregisterNodeResponse, error)
	// ノードが生存していることをcontrollerに通知する。
	Ping(ctx context.Context, in *PingNodeRequest, opts ...grpc.CallOption) (*PingNodeResponse, error)
	// 全ノードの一覧を取得する。
	ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (NodeService_ListNodesClient, error)
}

type nodeServiceClient struct {
	cc *grpc.ClientConn
}

func NewNodeServiceClient(cc *grpc.ClientConn) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error) {
	out := new(RegisterNodeResponse)
	err := c.cc.Invoke(ctx, "/elton.v2.NodeService/RegisterNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) UnregisterNode(ctx context.Context, in *UnregisterNodeRequest, opts ...grpc.CallOption) (*UnregisterNodeResponse, error) {
	out := new(UnregisterNodeResponse)
	err := c.cc.Invoke(ctx, "/elton.v2.NodeService/UnregisterNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) Ping(ctx context.Context, in *PingNodeRequest, opts ...grpc.CallOption) (*PingNodeResponse, error) {
	out := new(PingNodeResponse)
	err := c.cc.Invoke(ctx, "/elton.v2.NodeService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (NodeService_ListNodesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_NodeService_serviceDesc.Streams[0], "/elton.v2.NodeService/ListNodes", opts...)
	if err != nil {
		return nil, err
	}
	x := &nodeServiceListNodesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NodeService_ListNodesClient interface {
	Recv() (*ListNodesResponse, error)
	grpc.ClientStream
}

type nodeServiceListNodesClient struct {
	grpc.ClientStream
}

func (x *nodeServiceListNodesClient) Recv() (*ListNodesResponse, error) {
	m := new(ListNodesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NodeServiceServer is the server API for NodeService service.
type NodeServiceServer interface {
	// クラスタに参加するときや、ノードの構成変更をしたときに呼び出すAPI。
	// ノードの情報を登録・更新をする。
	RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error)
	// クラスタから脱退するときに呼び出すAPI。
	// ノードの退避処理を行い、ノードの情報を削除する。
	UnregisterNode(context.Context, *UnregisterNodeRequest) (*UnregisterNodeResponse, error)
	// ノードが生存していることをcontrollerに通知する。
	Ping(context.Context, *PingNodeRequest) (*PingNodeResponse, error)
	// 全ノードの一覧を取得する。
	ListNodes(*ListNodesRequest, NodeService_ListNodesServer) error
}

// UnimplementedNodeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedNodeServiceServer struct {
}

func (*UnimplementedNodeServiceServer) RegisterNode(ctx context.Context, req *RegisterNodeRequest) (*RegisterNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterNode not implemented")
}
func (*UnimplementedNodeServiceServer) UnregisterNode(ctx context.Context, req *UnregisterNodeRequest) (*UnregisterNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterNode not implemented")
}
func (*UnimplementedNodeServiceServer) Ping(ctx context.Context, req *PingNodeRequest) (*PingNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedNodeServiceServer) ListNodes(req *ListNodesRequest, srv NodeService_ListNodesServer) error {
	return status.Errorf(codes.Unimplemented, "method ListNodes not implemented")
}

func RegisterNodeServiceServer(s *grpc.Server, srv NodeServiceServer) {
	s.RegisterService(&_NodeService_serviceDesc, srv)
}

func _NodeService_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).RegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/elton.v2.NodeService/RegisterNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).RegisterNode(ctx, req.(*RegisterNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_UnregisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).UnregisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/elton.v2.NodeService/UnregisterNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).UnregisterNode(ctx, req.(*UnregisterNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/elton.v2.NodeService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Ping(ctx, req.(*PingNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_ListNodes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListNodesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeServiceServer).ListNodes(m, &nodeServiceListNodesServer{stream})
}

type NodeService_ListNodesServer interface {
	Send(*ListNodesResponse) error
	grpc.ServerStream
}

type nodeServiceListNodesServer struct {
	grpc.ServerStream
}

func (x *nodeServiceListNodesServer) Send(m *ListNodesResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _NodeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "elton.v2.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterNode",
			Handler:    _NodeService_RegisterNode_Handler,
		},
		{
			MethodName: "UnregisterNode",
			Handler:    _NodeService_UnregisterNode_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _NodeService_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListNodes",
			Handler:       _NodeService_ListNodes_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "node.proto",
}
